### PR TITLE
Change default image as the previous one expires

### PR DESCRIPTION
**Pull request by keanecjy**

### CODE REVIEW

**Review by tanruiquan — COMMENTED** [review]
It's meant to indicate that the trip name is compulsory haha

**Comment by keanecjy** [comment]
oh ok haha

**Comment by keanecjy** [comment]
its a bit strange tho, cuz we dont put * for plan name

**Comment by keanecjy** [comment]
@tanruiquan updated the PR to fix something else

**Comment by tanruiquan** [comment]
> its a bit strange tho, cuz we dont put * for plan name

I think just be consistent, either put for all or don't put for all. I'm ok with both ways.

**Review by tanruiquan — APPROVED** [review]

**Pull request merged**
